### ISSUE TITLE
代码有一些小bug

### ISSUE THREAD

**Issue by Wyxdm** [AaronNZH/Boosting-Few-shot-3D-Point-Cloud-Segmentation-via-Query-Guided-Enhancement#1]
尊敬的作者：
感谢您做出的优秀工作并开源了代码：但是在依照您的代码进行复现的过程中，发现代码有一些遗漏或者小bug：例如：
1.  /runs/eval.py的第15行：“from models.proto_learner import ProtoLearner”，但是在models文件夹下面并没有ProtoLearner文件。
2. models/attention.py的第72行，channe -> channel；
在更新代码的过程中有遗漏或者失误非常正常，请问您是否可以分享更加完善的代码，感谢！
再次感谢您对社区做出的贡献！

**Comment by AaronNZH** [comment]
感谢您的指正
