### ISSUE TITLE
关于性能抖动

### ISSUE THREAD

**Issue by Wyxdm** [AaronNZH/Boosting-Few-shot-3D-Point-Cloud-Segmentation-via-Query-Guided-Enhancement#2]
尊敬的作者：
感谢您所做出的优秀工作并开源了代码！在这边有个小问题请教一下您！在根据您的代码复现的过程中，多次复现的性能结果出现了比较明显的性能抖动， 请问您在实验和性能report的时候如何考虑这种因素带来的影响呢？(在2D图像上的小样本分割算法似乎普遍也有这个现象）
期待您的回复。
祝好！

**Comment by AaronNZH** [comment]
可以多次实验取平均
